openapi: 3.0.1
info:
  title: 판례 검색 API
  description: 키워드로 판례를 검색합니다.
  version: "1.0.0"
servers:
  - url: https://<나중에-render에서-생성된-주소>
paths:
  /search-case:
    get:
      summary: 판례 검색
      operationId: searchCase
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 검색 결과
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        사건명:
                          type: string
                        사건번호:
                          type: string
                        선고일자:
                          type: string
                        판시사항:
                          type: string